### ISSUE TITLE
Unable to find version `v1`

### ISSUE THREAD

**Issue by mfansler** [snakemake/snakemake-github-action#15]
Using the code

```yaml
- name: Snakemake Linting
  uses: snakemake/snakemake-github-action@v1
  with:
    directory: '.'
    args: '--lint'
```

I get the error

> Error: Unable to resolve action `snakemake/snakemake-github-action@v1`, unable to find version `v1`

Seems like GHA doesn't automatically recognize semantic versioning.
