### ISSUE TITLE
configure strict priorities by executing conda config --set channel_priority strict

### ISSUE THREAD

**Issue by seb-mueller** [snakemake/snakemake-github-action#23]
Recently, running snakemake-github-action CI started giving me:
  
>Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct >environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please 

The solutions was to change `stagin` to:
```
stagein: "conda config --set channel_priority strict"
```

Full context in `.github/workflows/main.yaml`:

```
jobs:
  Test_workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: myworkflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority strict"
        args: "--use-conda --cores 1 -rp --show-failed-logs all"
```
I thought to share it in case someone else comes accross the same
