### ISSUE TITLE
Save png of DAG using this action

### ISSUE THREAD

**Issue by colinbrislawn** [snakemake/snakemake-github-action#3]
I usually run this to make save DAGs
```bash
snakemake --dag --forceall --configfile config/example.yml | dot -Tpng > outdir/full-graph.png
```

So I tried this
```yml
    - name: Save full DAG
      uses: snakemake/snakemake-github-action@v1.4.1
      with:
        args: '--dag --forceall --configfile config/example.yml | dot -Tpng > outdir/full-graph.png'
```
but of course this was not escaped properly.

Is there a way to pipe the output DAG like I'm doing here? What is the GitHub Actions ™️  way of getting these graphs?

**Comment by kelly-sovacool** [comment]
Idea for a potential workaround: write a rule in your snakemake to generate the DAG, then use GitHub Actions to run the rule.

Snakefile:
```
rule write_dag:
    output:
        png='outdir/full-graph.png'
    shell:
        '''
        snakemake --dag --forceall --configfile config/example.yml | dot -Tpng > {output.png}
        '''  
```

In your GitHub Actions workflow:
```
    - name: Save full DAG
      uses: snakemake/snakemake-github-action@v1.4.1
      with:
        args: 'write_dag'
```
